"""
Dutch dictionary lookup - lemma to English gloss, POS-aware.

Supports two backends:
  1. SQLite (preferred) - memory-efficient, ~5MB on disk, zero RAM overhead.
     Generated by: python scripts/convert_dictionary_to_sqlite.py
  2. JSON (fallback) - loads entire ~63MB file into ~300MB of RAM.
     Used when SQLite file doesn't exist (e.g. local dev without conversion).

Uses POS to return correct meaning (e.g. olie+NOUN=oil, not verb form).
Provides authoritative external links (Mijnwoordenboek, Woorden.org, Wiktionary).
"""

import json
import sqlite3
from pathlib import Path
from typing import Optional

_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "dictionary"
DEFAULT_DB_PATH = _DATA_DIR / "dutch_glosses.db"
DEFAULT_JSON_PATH = _DATA_DIR / "dutch_glosses.json"

MIJNWOORDENBOEK_URL = "https://www.mijnwoordenboek.nl/vertaal/NL/EN/{word}"
WOORDEN_ORG_URL = "https://www.woorden.org/woord/{word}"
WIKTIONARY_URL = "https://en.wiktionary.org/wiki/{word}"

FALLBACK_GLOSS_EN: dict[str, str] = {
    "goedkoop": "cheap",
    "goedkoper": "cheaper",
    "makkelijk": "easy",
    "makkelijker": "easier",
    "duur": "expensive",
    "duurder": "more expensive",
    "gaan": "to go",
    "komen": "to come",
    "gebruiken": "to use",
    "olie": "oil",
    "water": "water",
    "land": "country",
    "landen": "countries",
    "brandstof": "fuel",
    "prijs": "price",
    "prijzen": "prices",
    "fatbike": "fat bike",
    "fatbikes": "fat bikes",
    "verboden": "forbidden",
    "advies": "advice",
    "inwoner": "resident",
    "inwoners": "residents",
}


class DictionaryLookup:
    """
    Lookup Dutch lemmas to English glosses, POS-aware.

    Tries SQLite first (near-zero memory). Falls back to loading the JSON
    file into memory if the SQLite database doesn't exist.
    """

    def __init__(
        self,
        db_path: Optional[Path] = None,
        json_path: Optional[Path] = None,
    ):
        self._conn: Optional[sqlite3.Connection] = None
        self._cache: Optional[dict] = None

        db = db_path or DEFAULT_DB_PATH
        if db.exists():
            self._conn = sqlite3.connect(str(db), check_same_thread=False)
            self._conn.row_factory = sqlite3.Row
            return

        jp = json_path or DEFAULT_JSON_PATH
        if jp.exists():
            with open(jp, encoding="utf-8") as f:
                self._cache = json.load(f)

    # -- Public API (unchanged interface) ------------------------------------

    def lookup(self, lemma: str, pos: Optional[str] = None) -> Optional[str]:
        entry = self._get_entry(lemma, pos)
        if entry is None:
            return None
        if isinstance(entry, str):
            return entry
        return entry.get("gloss")

    def lookup_with_example(self, lemma: str, pos: Optional[str] = None) -> Optional[dict]:
        entry = self._get_entry(lemma, pos)
        gloss = None
        gloss_en = None
        example = None
        if entry is not None:
            if isinstance(entry, str):
                gloss = entry
            else:
                gloss = entry.get("gloss")
                gloss_en = entry.get("gloss_en") or None
                example = entry.get("example") or None
        if gloss_en is None:
            gloss_en = FALLBACK_GLOSS_EN.get(lemma.lower().strip())
        if entry is None and gloss_en is None:
            return None
        return {"gloss": gloss, "gloss_en": gloss_en, "example": example}

    def get_links(self, lemma: str) -> dict[str, str]:
        word = lemma.strip()
        return {
            "Mijnwoordenboek": MIJNWOORDENBOEK_URL.format(word=word),
            "Woorden.org": WOORDEN_ORG_URL.format(word=word),
            "Wiktionary": WIKTIONARY_URL.format(word=word),
        }

    @property
    def is_loaded(self) -> bool:
        return self._conn is not None or (self._cache is not None and len(self._cache) > 0)

    # -- Internal dispatch ---------------------------------------------------

    def _get_entry(self, lemma: str, pos: Optional[str] = None):
        if self._conn is not None:
            return self._get_entry_sqlite(lemma, pos)
        if self._cache is not None:
            return self._get_entry_json(lemma, pos)
        return None

    def _get_entry_sqlite(self, lemma: str, pos: Optional[str] = None):
        key = lemma.lower().strip()
        if pos:
            row = self._conn.execute(
                "SELECT gloss, gloss_en, example FROM glosses WHERE lemma = ? AND pos = ?",
                (key, pos),
            ).fetchone()
            if row:
                return {"gloss": row["gloss"], "gloss_en": row["gloss_en"], "example": row["example"]}
            # Try OTHER fallback
            row = self._conn.execute(
                "SELECT gloss, gloss_en, example FROM glosses WHERE lemma = ? AND pos = 'OTHER'",
                (key,),
            ).fetchone()
            if row:
                return {"gloss": row["gloss"], "gloss_en": row["gloss_en"], "example": row["example"]}
        # No POS or no match: return first available entry
        row = self._conn.execute(
            "SELECT gloss, gloss_en, example FROM glosses WHERE lemma = ? LIMIT 1",
            (key,),
        ).fetchone()
        if row:
            return {"gloss": row["gloss"], "gloss_en": row["gloss_en"], "example": row["example"]}
        return None

    def _get_entry_json(self, lemma: str, pos: Optional[str] = None):
        """JSON-based lookup (legacy, high memory)."""
        key = lemma.lower().strip()
        if key not in self._cache:
            return None
        poses = self._cache[key]
        if isinstance(poses, str):
            return poses
        if pos and pos in poses:
            return poses[pos]
        if pos and "OTHER" in poses:
            return poses["OTHER"]
        return next(iter(poses.values()), None) if poses else None


# Module-level singleton (lazy)
_lookup: Optional[DictionaryLookup] = None


def get_lookup() -> DictionaryLookup:
    """Get shared DictionaryLookup instance."""
    global _lookup
    if _lookup is None:
        _lookup = DictionaryLookup()
    return _lookup
